import { Edit3, Clock, FileText } from "lucide-react";
import BentoCard from "./bentocard";

// Define the shape of the data we expect
interface NoteData {
  id: number;
  title: string;
  date: string;
  preview: string;
}

interface RecentNoteProps {
  className?: string;
  note?: NoteData | null;
  onEdit?: (id: number) => void;
}

// destructure onEdit here so it is available in the function scope
export default function RecentNote({
  className = "",
  note,
  onEdit,
}: RecentNoteProps) {
  // if no note exists, show a placeholder
  if (!note) {
    return (
      <BentoCard
        title="Recently viewed note"
        className={`group relative ${className}`}
      >
        <div className="flex flex-col items-center justify-center h-full text-slate-500 opacity-60">
          <FileText size={48} className="mb-4 opacity-50" />
          <p className="text-sm font-medium uppercase tracking-widest">
            No notes yet
          </p>
        </div>
      </BentoCard>
    );
  }

  return (
    <BentoCard
      title="Recently viewed note"
      className={`group relative ${className}`}
    >
      {/* Header */}
      <div className="flex items-center justify-between mb-6 border-b border-white/5 pb-4">
        <div className="overflow-hidden">
          <h2 className="text-2xl font-bold text-white tracking-tight truncate pr-4">
            {note.title}
          </h2>
          <div className="flex items-center gap-3 mt-2 text-xs font-medium text-slate-400 uppercase tracking-widest">
            <span className="flex items-center gap-1">
              <Clock size={12} /> {note.date}
            </span>
            {/* Optional: You could add tags here if you implement categories later */}
          </div>
        </div>

        <button
          onClick={() => onEdit && onEdit(note.id)} // trigger the callback
          className="p-3 rounded-full bg-white/5 hover:bg-white/10 border
        border-white/5 transition-all hover:scale-105 active:scale-90 shrink-0"
        >
          <Edit3 size={18} className="text-white/70" />
        </button>
      </div>

      {/* Note Content Preview */}
      <div className="space-y-4 opacity-80 font-serif text-lg leading-relaxed text-slate-200 mask-image-b h-full overflow-hidden">
        {/* We display the preview text generated by NotesView */}
        <p className="line-clamp-6">
          {note.preview || "No additional text..."}
        </p>

        {/* Decorative elements to maintain the 'Editor' aesthetic */}
        <div className="pl-4 border-l-2 border-indigo-500/50 italic text-slate-500 text-sm mt-4">
          Reading mode
        </div>
      </div>
    </BentoCard>
  );
}
